#! /usr/bin/env bash

RED="\033[31m"
YELLOW="\033[33m"
RESET="\033[0m"
if [ `tput colors` -ne 256 ]; then
    echo -e $RED"This terminal does not support 256 color. 'tput colors' for more detail"$RESET
else
    echo -e $YELLOW"This terminal supports 256 color"$RESET
fi
