#! /usr/bin/env bash

RED="\033[31m"
YELLOW="\033[33m"
RESET="\033[0m"
if [ `tput colors` -ne 256 ]; then
    ./terminalcolors.py
    echo -e $RESET
    echo -e $RED"This terminal does not support 256 color. 'tput colors' for more detail"$RESET
    echo -e $YELLOW"Can you see 256 colors? Then, check \$TERM."$RESET
    echo -e $YELLOW"Your current \$TERM is '$RED$TERM$YELLOW'"$RESET
else
    echo -e $YELLOW"This terminal supports 256 color"$RESET
fi
